# 应用服务 WEB 访问端口
server:
  port: 8080
# 应用名称
spring:
  redis:
    port: 31642
    password: 310012
    host: 172.16.4.250
    database: 2
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 5000   # 关闭超时时间


